// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr1XVNbkUnL6KACJcQ8DkzbwLFBFyVWno',
    appId: '1:996421168796:web:1c1ed13a4d6b05b0c2c759',
    messagingSenderId: '996421168796',
    projectId: 'stackup-64824',
    authDomain: 'stackup-64824.firebaseapp.com',
    storageBucket: 'stackup-64824.firebasestorage.app',
    measurementId: 'G-92E34S6C8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAabx_BTnz9N0VVI23OX8BnJWpn4jMbq-E',
    appId: '1:996421168796:android:34313e038c400543c2c759',
    messagingSenderId: '996421168796',
    projectId: 'stackup-64824',
    storageBucket: 'stackup-64824.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxpgT8vG5Kt4xQ8ajzZstgHEw3f2uN0zw',
    appId: '1:996421168796:ios:af1cd7c2c5fef581c2c759',
    messagingSenderId: '996421168796',
    projectId: 'stackup-64824',
    storageBucket: 'stackup-64824.firebasestorage.app',
    iosBundleId: 'com.example.stackup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxpgT8vG5Kt4xQ8ajzZstgHEw3f2uN0zw',
    appId: '1:996421168796:ios:af1cd7c2c5fef581c2c759',
    messagingSenderId: '996421168796',
    projectId: 'stackup-64824',
    storageBucket: 'stackup-64824.firebasestorage.app',
    iosBundleId: 'com.example.stackup',
  );
}
